### ISSUE TITLE
Feature: Disable run button

### ISSUE THREAD

**Issue by atomashevic** [kiran-machhewar/Markdown-Enhanced-Code-Block#5]
I was looking for a good VSCode extension which just places "Copy" button above code blocks and this one does a great job. 

I'm not interested in "Run" part of the extension, so in terms on keeping the interface as simple as possible, I would like to have the option to disable the "Run" button and just keep "Copy".

**Comment by kiran-machhewar** [comment]
Sure, makes sense. Let me add configuration to disable run button. Will release an update and will let you know here.

**Comment by kiran-machhewar** [comment]
@atomashevic  Extension is updated now, please get the latest version of extension and you should be able to disable the run button from configuration. Configuration name is "Disable Run button". 

https://user-images.githubusercontent.com/4792950/224530273-336b287e-ffe6-4231-ba78-1ba6cc95d4c7.mov

**Comment by atomashevic** [comment]
Great, I tested it and it works, thanks!

I've also noticed a bug where both buttons don't show if language name after ` ``` ` is one letter like ` ```r ` or ` ```c ` (any letter). It works for any string with more than 1 character. 

![image](https://user-images.githubusercontent.com/39856297/224963717-a5f11692-c3a0-4a5a-8533-be9c61e6b517.png)
